spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:todotest
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG